### ISSUE TITLE
Issue: No GitHub workflows

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury-subgraph#2]
There's no GitHib workflows to trigger the CI (running of tests against pushed code).

Inspiration can be drawn from https://github.com/windranger-io/windranger-treasury/tree/main/.github/workflows

**Comment by grezle** [comment]
See here: 

- https://github.com/windranger-io/windranger-treasury-subgraph/blob/main/.github/workflows/main.yml
- https://github.com/windranger-io/windranger-treasury-subgraph/runs/6583857327?check_suite_focus=true

**Comment by CjHare** [comment]
I stand corrected 👍
