### ISSUE TITLE
Issue: Hard coded addresses in test utils

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury-subgraph#3]
The test have a util that uses constants for contract addresses. A very brittle approach and as different envs may have different contract addresses this could prevent the tests from being quickly & easily usable across envs.

https://github.com/windranger-io/windranger-treasury-subgraph/blob/65c488342fc686f16e712585a2e086216e041bae/tests/utils.ts#L23

**Comment by CjHare** [comment]
How are contract deployment addresses chosen, is that done by the test framework i.e. deterministically?

_I was assuming it was just using the network it deployed to_

**Comment by grezle** [comment]
Matchstick isn't concerning itself with the `schema.yaml` from what I can tell - it just lets you pass fake event data into the EventHandler mappings. The contract address is passed in in the calling signature of the `EventHandler` in the test, so what we're faking is the contracts existence and that it sent an event, then were just validating that the data was stored in the correct place in the graph.

**Comment by CjHare** [comment]
Oh, so it's doing effectively mocking of the contracts?

**Comment by grezle** [comment]
Yes exactly! Nothing has been deployed yet from what I am aware!

https://thegraph.com/docs/en/developer/matchstick/

**Comment by CjHare** [comment]
Ah 🤔 

When I go in and change an event in Bonds, how do we tell that the SubGraph will be broken when it's deployed?

_It sounds like it's a manual step_

**Comment by grezle** [comment]
I wrote a bash script to update the abis from the contract repo (`yarn run update-abis`), if we run that, then `codegen`, `build` and `test`, we should be able to spot any changes that would break the build. Everything is typed, so if something in the Event signature changes, it will break one of those steps.

**Comment by CjHare** [comment]
A scripted verifying that subgraph events match those from the 'upstream' Treasury repo sound good 👍 

_Later on that can be worked into a CI stream, with a trigger from the upstream Treasury repo on master push_ 🤔
